project:
  type: book

book:
  title: "R for Research"
  subtitle: "A Companion for Statistical Analysis with R for Reproducible Research"
  author: "Enayetur Raheem"
  date:  "2023/02/21"
  chapters:
    - index.qmd
    - introduction.qmd
    - r.qmd
    - research-process.qmd
    - analytic-process.qmd
    - applications.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



